### ISSUE TITLE
[BUG] Frame buffer specification always includes divisions from delta 0 onwards

### ISSUE THREAD

**Issue by KristinaUlicna** [Janelia-Trackathon-2023/traccuracy#100]
Playing with the `ctc.ipynb` data, I'm trying to change the `metrics_kwargs` argument to include a different range of frame buffers to compute the metrics for, as follows:

```
iou_results = run_metrics(
    gt_data=gt_data, 
    pred_data=pred_data, 
    matcher=IOUMatched, 
    matcher_kwargs=dict(
        iou_threshold=iou
    ),
    metrics=[DivisionMetrics], 
    metrics_kwargs=dict(
        frame_buffer=(1, )
    ),
)
pp.pprint(iou_results["DivisionMetrics"])
```

where `iou` is somewhere between 0.3-0.9. 

The output always includes the results of `frame_buffer = 0`, even when not specified:

```
IoU Threshold : 0.9
Matching frames: 100%|██████████| 92/92 [00:05<00:00, 16.02it/s]
0.9
{   'Frame Buffer 0': {   'Division F1': 0.4318181818181818,
                          'Division Precision': 0.4175824175824176,
                          'Division Recall': 0.4470588235294118,
                          'False Negative Divisions': 94,
                          'False Positive Divisions': 106,
                          'Mitotic Branching Correctness': 0.2753623188405797,
                          'True Positive Divisions': 76},
    'Frame Buffer 1': {   'Division F1': 0.4318181818181818,
                          'Division Precision': 0.4175824175824176,
                          'Division Recall': 0.4470588235294118,
                          'False Negative Divisions': 94,
                          'False Positive Divisions': 106,
                          'Mitotic Branching Correctness': 0.2753623188405797,
                          'True Positive Divisions': 76}}
```

I'm not sure if this is a **bug** _per se_, but it may be beneficial to change the argument type from `tuple[int]` to an `max_int` in this case, where 2 would compute all frame buffers up to 2, _i.e._ 0, 1 as well as 2.

**Comment by bentaculum** [comment]
Hi @msschwartz21, have you already had a chance to look this one? I just ran into this as well. As for Kristina above, for me different frame buffers, e.g. 0 vs 100, are leading to the same metrics, seems to be a bug.

**Comment by msschwartz21** [comment]
Hey Ben, I thought the issue here was that a frame buffer of 0 is always calculated even when another value is requested. Is that the issue you are seeing or is it something else?

**Comment by bentaculum** [comment]
It seems two-fold to me, frame buffer 0 is always calculated, and e.g. in our example https://github.com/Janelia-Trackathon-2023/traccuracy/blob/main/examples/ctc.ipynb the Division metrics results do not change no matter which number I choose as frame.

**Comment by msschwartz21** [comment]
I'm wondering if there are just no shifted divisions in the example predicted graph that we are using in the notebook. This test case https://github.com/Janelia-Trackathon-2023/traccuracy/blob/main/tests/metrics/test_divisions.py seems like it should cover what you are describing, e.g. different frame buffers produce different metrics that appropriately detect shifted divisions.

**Comment by bentaculum** [comment]
Thanks for checking, minimal example ftw. Sorry for the noise.

**Comment by msschwartz21** [comment]
No worries! I'm just celebrating that we had the appropriate test case in our test suite 😂
