### ISSUE TITLE
[DOCS] Update `ctc.ipynb` notebook with note about `[SSL: CERTIFICATE_VERIFY_FAILED]`

### ISSUE THREAD

**Issue by KristinaUlicna** [Janelia-Trackathon-2023/traccuracy#102]
Let's notify the user about what to do if (if!) downloading the data from CTC website throws a certificate error. Raised in & will resolve #84

**Comment by msschwartz21** [comment]
Can you also enable logging in the notebook when you make this other change? 

`logging.basicConfig(level=logging.INFO)`

**Comment by KristinaUlicna** [comment]
Already done in #105 🚀
