### ISSUE TITLE
`imagecodecs` dependency and installation issues

### ISSUE THREAD

**Issue by msschwartz21** [Janelia-Trackathon-2023/traccuracy#13]
`imagecodecs` is required in order to read the tiffs associated with the Cell Tracking Challenge. Currently pip installation of `imagecodecs` fails on macs, but can be resolved by first installing it with mamba prior to pip installation of the `cell-tracking-metrics` package.

- Should we make this dependency optional since only the ctc loader will use it? 
- Should we add a note in docs about how to resolve the installation issue on macs?

**Comment by tlambert03** [comment]
I would imagine this is fixed now... imagecodecs [now offers wheels on PyPI](https://pypi.org/project/imagecodecs/#files) for macOS on both x86_64 (intel) and arm64 (m1) for python 3.9-3.12
