### ISSUE TITLE
Let IOU matching fallback to location keys if there is no label key

### ISSUE THREAD

**Issue by adjavon** [Janelia-Trackathon-2023/traccuracy#28]
### Description

The IOU Matcher currently relies on the label-key to find objects in the detections. When the location is available, it would be nice to use that instead. This would be useful both in cases where the label key is missing, or even where we have semantic-like detections instead of instance-like detections.

**Comment by msschwartz21** [comment]
We're going to leave this task to the user and require that they sanitize/format their data appropriately before it passing it into traccuracy.
