### ISSUE TITLE
Create and enforce set of valid graph annotation keys

### ISSUE THREAD

**Issue by cmalinmayor** [Janelia-Trackathon-2023/traccuracy#43]
- [x] add Enum for valid node attrs and edge attrs in track_graph.py (make values be the strings we already have, so that the nx graph is inspectable)
- [x] `set_node_attribute` (and `set_edge_attribute`) only allows setting the valid node/edge attrs from the enum, and throws error otherwise (with descriptive message about adding attr to enum). If people need custom attrs, they add them to enum, which ensures no overlap of string representations.
- [x] update every place we annotate the graph to use the enums instead of hard coded strings
- [x] Check if frame key and location key overlap with enum strings upon initialization of TrackGraph

**Comment by cmalinmayor** [comment]
Check if frame key and location key overlap with enum strings upon initialization of TrackGraph

**Comment by msschwartz21** [comment]
Closed in #47 and #48
