### ISSUE TITLE
`"is_intertrack_edge"` is used but not annotated on graphs in CTC errors

### ISSUE THREAD

**Issue by msschwartz21** [Janelia-Trackathon-2023/traccuracy#45]
I noticed that we never annotate any edges as `"is_intertrack_edge"`, but the way this is written assumes that the attribute exists. 

https://github.com/Janelia-Trackathon-2023/traccuracy/blob/f8c982c57b8aa92ac8ab5410318ad2b20c0c6f76/src/traccuracy/track_errors/_ctc.py#L131-L132

In the test case, if I comment out the line where we set it on the input graph, the test fails.

https://github.com/Janelia-Trackathon-2023/traccuracy/blob/f8c982c57b8aa92ac8ab5410318ad2b20c0c6f76/tests/track_errors/test_ctc_errors.py#L76

Are we missing a bug here? @DragaDoncila can you take a look? I don't really understand the ctc errors well enough to make an informed evaluation.

**Comment by msschwartz21** [comment]
Caroline tracked down the annotation of `"is_intertrack_edge"` to the ctc loader class

https://github.com/Janelia-Trackathon-2023/traccuracy/blob/f8c982c57b8aa92ac8ab5410318ad2b20c0c6f76/src/traccuracy/loaders/_ctc.py#L113-L118

I think we should move this annotation step to the function where we annotate the graph with ctc related errors in `traccuracy.track_errors._ctc.evaluate_ctc_events`.

**Comment by DragaDoncila** [comment]
@msschwartz21 thanks for raising! 

For the `TRA` metric there is a dedicated error count for cases where there is an incorrect parent connection (counted under `wrong semantic` or `ws` edge errors. Essentially an intertrack edge is any edge connecting two nodes with different track IDs. We don't actually have a concept of `track-id` though, right? 

In the `CTC` loader we annotate all parent connections with `is_intertrack_edge=1` [here](https://github.com/Janelia-Trackathon-2023/traccuracy/blob/f8c982c57b8aa92ac8ab5410318ad2b20c0c6f76/src/traccuracy/loaders/_ctc.py#L132), but not sure what the best option is for graphs loaded some other way - just set to 0 in `traccuracy.track_errors._ctc.evaluate_ctc_events` as you suggest, if it's not present, and warn that any `ws` errors won't be counted?
