### ISSUE TITLE
Where do we store the output of the benchmark for the current `main`?

### ISSUE THREAD

**Issue by bentaculum** [Janelia-Trackathon-2023/traccuracy#73]
I'm wondering where we are storing the results of the benchmarks for the current `main`, I'm a bit lost.
I would like to look at the table that the benchmark workflow produces, supposedly named `output.json`: https://github.com/Janelia-Trackathon-2023/traccuracy/blob/main/.github/workflows/benchmark-report.yml

Things I do find:
- I'm seeing the benchmark badge in the README, with the plots, quite nice.
- Just found the entry of the run benchmark for the last merge in github actions: https://github.com/Janelia-Trackathon-2023/traccuracy/actions/runs/6694074248/job/18196239967
- And in the branch `gh-pages` there is a csv file with all the benchmark results ever obtained by github actions.

**Comment by cmalinmayor** [comment]
@msschwartz21 I think this is for you

**Comment by msschwartz21** [comment]
The benchmarking data from the workflows that run on main are saved in `data.js` on the `gh-pages` branch. For example, I think this is the start of the data entry from the most recent merge #59: https://github.com/Janelia-Trackathon-2023/traccuracy/blob/a8ba026f831f120fb2a6ebcef45c297f31779c75/dev/bench/data.js#L664-L733 The same data is displayed in the "Store benchmark results" part of the action.

This action doesn't explicitly generate any kind of diff table like we do on the PR workflow, but that's something we could add if needed.

**Comment by bentaculum** [comment]
Ok thanks. I think what we have in place is already great and will help us to avoid introducing slowdowns. If we realize that we are working on improving performance a lot we might want to come back to this.
