### ISSUE TITLE
Feature: Validation of Matchers and Metrics that work together

### ISSUE THREAD

**Issue by cmalinmayor** [Janelia-Trackathon-2023/traccuracy#83]
As we expand beyond CTC metrics, we know that certain matchers and metrics do not make sense to be run together because they make different assumptions. We want to formalize the assumptions that each matcher and metric makes, and perform some validation based on that formalization. 

Some example assumptions we have discussed include:

- one-to-one matching or one-to-many matching or many-to-one matching - does the matching allow multiple ground truth nodes to be matched to one predicted node, or vice versa? 
- matching on nodes vs matching on edges - this is potentially a subset of the above assumptions, but should be considered
- dense ground truth
- has segmentation mask

This validation could be done in run_metrics, or elsewhere. We need to pin down the concepts and then determine where/how in the code to put the validation (and then document!).

**Comment by msschwartz21** [comment]
Just want to drop a thought here after Caroline and I were discussing this issue. 

Given that we have a very limited number of matchers and metrics, it might be easier to just hardcode a list of compatible matchers/metrics on each matcher/metric object. The we can just be thoughtful about what is compatible and not have to come up with a super clever system for determining it on an automated basis.
