### ISSUE TITLE
API Update: Instantiate Matcher and Metrics classes before passing into run_metrics

### ISSUE THREAD

**Issue by cmalinmayor** [Janelia-Trackathon-2023/traccuracy#87]
Instantiating Matcher and Metrics classes before passing into run_metrics function avoids the kwargs arguments, which are fairly messy. This requires changing the API of the matcher to pass the data into the `compute` method instead of into the constructor. Make this change concurrently with or after #86 .

**Comment by msschwartz21** [comment]
Instead of returning a list of tuples return two dictionaries that provides lookup between nodes in either direction.
