### ISSUE TITLE
Project Structure: Public vs Private Classes and Functions

### ISSUE THREAD

**Issue by cmalinmayor** [Janelia-Trackathon-2023/traccuracy#90]
Based on our discussion at the 10/30/23 working group meeting:

- Anything that is called "externally" even between objects in the library should be public - based on quick scan through the code, I don't think we violate this very often, but we should go through and check.
- The reason why we have underscores in front every file (e.g. `_tracking_graph.py`) is because keeping the module private while exposing the specific public class allows us to hide utilities. It is unclear from the notes if we decided to keep this convention or not - @msschwartz21 @DragaDoncila @tlambert03 @bentaculum do you remember what we decided? We do also have some `_utils.py` files, which we can use to store utilities. Let's decide on a standard way to do this, whether inside the file or in a separate _utils.py file.

**Comment by msschwartz21** [comment]
Caroline & Morgan decision: Leave the underscores and work on moving key imports higher up so that they are easier to access
